# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.6

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/LineLength:
  Max: 120

Naming/PredicateName:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Style/Documentation:
  Enabled: false
