default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: university_api_development

test:
  <<: *default
  database: university_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: university_api_production
